# Generated by Django 4.2.11 on 2024-04-16 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ala', models.CharField(choices=[('Ala 1', 'Ala 1'), ('Ala 2', 'Ala 2'), ('Ala 3', 'Ala 3'), ('Ala 4', 'Ala 4')], max_length=10, verbose_name='Ala')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Limpeza',
                'verbose_name_plural': 'Limpezas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ala', models.CharField(choices=[('Ala 1', 'Ala 1'), ('Ala 2', 'Ala 2'), ('Ala 3', 'Ala 3'), ('Ala 4', 'Ala 4')], max_length=10, verbose_name='Ala')),
                ('quarto', models.IntegerField(max_length=1, verbose_name='Quarto')),
                ('lider', models.BooleanField(default=False, verbose_name='Lider de ala')),
                ('em_dia_limpeza', models.BooleanField(default=False, verbose_name='Em dia com a Limpeza')),
                ('em_dia_taxa', models.BooleanField(default=False, verbose_name='Em dia com a Taxa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=1000, verbose_name='comentario')),
                ('limpeza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LimpezaApp.limpeza', verbose_name='Limpeza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Gerenciador de Limpeza',
                'verbose_name_plural': 'Gerenciador de Limpezas',
            },
        ),
    ]
