# Generated by Django 4.2.11 on 2024-04-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LimpezaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
