# Generated by Django 4.2.11 on 2024-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LimpezaApp', '0004_acompanhamentolimpeza_comodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentolimpeza',
            name='comodo',
            field=models.CharField(blank=True, choices=[('Sala computadores', 'Sala computadores'), ('Sala estudos', 'Sala estudos'), ('Sala de baixo', 'Sala de baixo'), ('Sala de cima', 'Sala de cima'), ('Cozinha', 'Cozinha')], max_length=50, null=True, verbose_name='Comodo'),
        ),
    ]
