# Generated by Django 4.2.11 on 2024-04-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxaApp', '0002_acompanhamentotaxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentotaxa',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='comentario'),
        ),
    ]
