# Generated by Django 4.2.11 on 2024-04-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='quarto',
            field=models.IntegerField(verbose_name='Quarto'),
        ),
    ]
